### ISSUE TITLE
Next update checklist

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#38]
- [x] Finish installation documentation
- [x] Add section on Shifter execution
- [x] Put in run mode documentation
- [x] Make sure objective function handling and value passing is well clarified
