### ISSUE TITLE
Updating master

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#82]
Changes to be included:

- [x] Changing to be compatible with libEnsemble 0.8.0
- [x] With the above compatibility changes listed local-optimizers requiring gradient info should now be usable and dfols should now be available with APOSMM and not just as a standalone option
- [x] Better validation for configuration files #79 
- [x] Defaulting to job chain stop on error #75 
- [x] New `timeout` field available in setup to set code execution timeout (not available for serial Python execution yet)
- [x] New `force_executor` field available in setup. When true subprocess execution is always used even when the code is to be run in serial. (Can be useful to make an error-prone code more resilient against failure or to make sure serial Python code is launched through executor)
- [x] Better reliability for rsmpi job cancellation when rsopt is killed #54 
- [x] ~~Using mesh_grid is no longer required to just execute a single pass of a job chain #78 . Can now be executed through a single command `rsopt start ...`~~ (Implementing this uncovered some messy issues with a lack of proper handling for the sim_output for any kind of scan. Cutting this from the release to avoid more delay.)
- [x] New option to specify a file name for the history file dump (otherwise name is set by libEnsemble formatter) #84
