### ISSUE TITLE
Update master

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#91]
- [x] Latin Hypercube sampling now can accept use-defined seeds or set a random seed (#88)
- [x] Optimization workers no longer need a dedicated resource slot. (#76)
- [x] Improved handling of stdout/stderr when using rsmpi execution (#90)
- [x] Subsets of available rsmpi nodes may now be specified in the config file (908a99dc471e2f768b326c34bc0e2bdbe1fa9cbe)
- [x] Fixed bug in OPAL parser error messages  (#86)
- [x] `mesh_scan` now uses the `start` value if `samples: 1` (f5f6985c56bfd293a2f49c6ec0b25bde02e78f3e)
- [x] Fixed a bug in `mesh_scan` that was causing double evaluations of points when giving a custom mesh from file (2690dfad0c66900a1c809130888de876257d2e81).
